language: node_js
node_js:
  - 10
  - 12
env:
  - secure: "CCLQux5MfbB5YOKteRjYV9GpvIUYsEq+ws7DHw89G8/0ZyZ4DxKONL2TK3bZ+8Q295TzpvEPNLBnzUe9/ANSArGR63s49ao36S8s+rDajUuz0FfuWV5oFvtGw6703U4DbkdJqbLgmANslw0g7PCY82tq7U1lvmjNIvZZuugOSuo961w2uI8C0VZWoa25o/VsOHTFUoRKrmp3Nty8I/27Tv14NQH281CNfpLNs0O0BGZOSQljTBxZsJiNRd/SPqqbCHy06Ek0VaWnRDWguYL39LF127P3v4MRkBP07Dv/0QFc82hdnGnbGXg0flXliP/8UWx6urMc5k4khbkPonTsY3uW4Vs7fhu1jYBkrhzA+0mZIXdeY29N/cDRoFubx8glaAQ7ybsEuh48Tf+tF+325iaCA5a1H46/MbH67XNj6ItWLnUtFzDnbGwK+YC4anZhWLYWrtHUcnH1DhXq0OL+QwMFd+0h/3kC/R1vY4qyJlQnLAnwnhEaEze0MBj8KzfSpjDlCLI5XOF+ij8hh0bmkQjyNzyGorADFp4x6vlGZGiN5u8na+AgXuAYtraXl/dZnWLMMJssYMkp8heon/meOjioirShGzD5dZQLNcCu9hT+xccE6V9qPrZm3eAIxQvkUOiiiBbVPx7pBtlUHbfP2h8Q94JFhL0N5uw3bFovbGA="
deploy:
  provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
  on:
    repo: Laboratoria/bootcamp
    all_branches: true
